language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel
  
r_packages:
  - covr


after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack:
    secure: YYGw1ONNsTbfAXCNjJJk355lUXBo8YS56oJAwyXhWLRI/zx+1iydGKEWlteXBgyf3mTHz6DWkx2nq1dq+tGWSYoJL6x++K7wYSwAWuO6HZJ1lDBE8WvqY8zujYd35ptWsYHraeK9kUKwVijMRrX96thvjTWOHjYTydCfHp2B8ws=
